# SQLite version 3.x
#   gem install sqlite3
#
#   Ensure the SQLite 3 gem is defined in your Gemfile
#   gem 'sqlite3'
development:
  adapter: mysql2
  database: data_engineering_deveopment
  user: root
  host: localhost
  pool: 5
  timeout: 5000
test:
  adapter: mysql2
  database: data_engineering_test
  user: root
  host: localhost
  pool: 5
  timeout: 5000

